# Generated by Django 4.1 on 2022-08-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(choices=[('한국외국어대학교 글로벌캠퍼스', '한국외국어대학교 글로벌캠퍼스'), ('명지대학교', '명지대학교'), ('을지대학교', '을지대학교'), ('한양대학교 ERICA', '한양대학교 ERICA')], max_length=24, null=True, verbose_name='학교'),
        ),
    ]
