# Generated by Django 4.1 on 2022-08-22 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_postresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="university",
            field=models.CharField(
                choices=[
                    ("한국외국어대학교 글로벌", "한국외국어대학교 글로벌"),
                    ("명지대학교", "명지대학교"),
                    ("을지대학교", "을지대학교"),
                    ("한양대학교 ERICA", "한양대학교 ERICA"),
                ],
                max_length=24,
                null=True,
                verbose_name="학교",
            ),
        ),
        migrations.CreateModel(
            name="PersonalVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dict_json", models.JSONField(blank=True, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="아이디",
                    ),
                ),
            ],
            options={
                "verbose_name": "PersonalVote",
                "verbose_name_plural": "PersonalVote",
                "db_table": "PersonalVote",
            },
        ),
    ]
