# Generated by Django 4.1 on 2022-08-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('어드바이저', '어드바이저'), ('참가자', '참가자')], max_length=24, null=True, verbose_name='역할'),
        ),
    ]
