# Generated by Django 4.1 on 2022-08-21 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=17, null=True, verbose_name='팀명')),
                ('team_members', models.CharField(blank=True, max_length=30, null=True, verbose_name='팀원')),
                ('intro_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='한줄소개')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='이미지1')),
                ('imagesrc1', models.CharField(blank=True, max_length=40, null=True, verbose_name='이미지1 주소')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='이미지2')),
                ('imagesrc2', models.CharField(blank=True, max_length=40, null=True, verbose_name='이미지2 주소')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='이미지3')),
                ('imagesrc3', models.CharField(blank=True, max_length=40, null=True, verbose_name='이미지3 주소')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='이미지4')),
                ('imagesrc4', models.CharField(blank=True, max_length=40, null=True, verbose_name='이미지4 주소')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='아이디')),
            ],
            options={
                'verbose_name': 'PostResult',
                'verbose_name_plural': 'PostResult',
                'db_table': 'PostResult',
            },
        ),
    ]
